name: t22_setup       # Simply the name of our environment, choose something short and meaningful
channels:
- conda-forge       # this is where the conda packages will be fetched from
- defaults
dependencies:
- python=3.9
- pip               # we add pip to be able to use the pypi
- numpy>=1.20       # for all numeric python
- matplotlib>=3.5   # for basic plotting
- jupyter           # our chosen coding environment
- ipykernel         # we need this to make the conda env available to jupyter
- pandas>=1.4       # for all data wrangling needs
- openpyxl>=3.0     # to be able to open xls file with pandas
- requests          # to use python to query webpages
- pip:              # these packages come from the python package index (pypi)
  - bruges>=0.5     # geophysical tools
  - welly>=0.5      # well log tools
  - wellpathpy      # well deviation tools
  - segyio          # seismic loading tools
  - segysak         # higher level seismic loading tools
  - gio             # file loading tools
